export interface Fields {
  key: string;
  format?: 'number' | 'date';
}

export const PCOFields: Fields[] = [
  { key: 'conta' },
  { key: 'descricao' },
  { key: 'c_custo' },
  { key: 'item_conta' },
  { key: 'tipo' },
  { key: 'documento' },
  { key: 'item' },
  { key: 'produto' },
  { key: 'qtd', format: 'number' },
  { key: 'vlr_unit', format: 'number' },
  { key: 'total', format: 'number' },
  { key: 'emissao', format: 'date' },
  { key: 'data_prv', format: 'date' },
  { key: 'periodo' },
  { key: 'orcado', format: 'number' },
  { key: 'contin', format: 'number' },
  { key: 'solic', format: 'number' },
  { key: 'pedido', format: 'number' },
  { key: 'entr_nf', format: 'number' },
  { key: 'real_ctb', format: 'number' },
];

export const SSFields: Fields[] = [
  { key: 'ss' },
  { key: 'tag' },
  { key: 'nome_bem' },
  { key: 'descricao_servico' },
  { key: 'data' },
  { key: 'servico' },
  { key: 'centro_trabalho' },
  { key: 'solicitante' },
  { key: 'os' },
  { key: 'responsavel' },
];

export const ComprasFields: Fields[] = [
  { key: 'os' },
  { key: 'sc' },
  { key: 'item' },
  { key: 'produto' },
  { key: 'descricao' },
  { key: 'quantidade' },
  { key: 'emissao' },
  { key: 'aplicacao' },
  { key: 'observacao' },
  { key: 'cotacao' },
  { key: 'pc' },
  { key: 'dt_aprovacao_n1' },
  { key: 'dt_aprovacao_n2' },
  { key: 'dt_aprovacao_n3' },
  { key: 'quantidade_ja_entregue' },
  { key: 'ja_emitiu_fornecedor' },
  { key: 'valor_total' },
  { key: 'status_sc' },
  { key: 'status_pc' },
  { key: 'previsao_entrega' },
  { key: 'pc_eliminado_residuo' },
  { key: 'motivo_eliminado_residuo' },
  { key: 'sc_eliminado_residuo' },
  { key: 'data_pc' },
  { key: 'conta_pc' },
  { key: 'centro_custo_pc' },
  { key: 'solicitante' },
  { key: 'requisitante' },
  { key: 'fornecedor' },
  { key: 'tipo_pagamento' },
  { key: 'cod_aprovador_n1' },
  { key: 'cod_aprovador_n2' },
  { key: 'cod_aprovador_n3' },
];
